# Site settings
title: Nzaba
description: Ray of sunshine.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Raymond Nzaba
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: CS/Stats
email: rsaitoti20@amherst.edu
twitter_username: https://twitter.com/raynzaba
github_username:  https://github.com/Nzaba
gplus_username:  https://plus.google.com/u/0/+raymondnzaba

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
