title: Raymond
description: My personal portfolio.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Raymond Nzaba
user_description: Hi, I am Ray, a senior at Amherst College. I'm looking for full time opportunities to diversify my skill set. I am interested in developing a wide range of skills in diverse fields that would complement each other in unexpected ways. My professional interests include Program/Product Management, Consulting and Software Development.
user_title: Raymond N Saitoti.
email: rsaitoti20@amherst.edu
twitter_username: https://twitter.com/raynzaba
github_username:  https://github.com/Nzaba
gplus_username:  https://plus.google.com/u/0/+raymondnzaba

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
